[package]
name = "timsrust-tdf"
version.workspace = true
edition.workspace = true
repository.workspace = true
description = "Reader for the Bruker TDF timsTOF file format (.d folders)"
license = "Apache-2.0"

[dependencies]
timsrust-core = { workspace = true, features = ["io"] }
serde = { workspace = true, features = ["derive"] }
lzf = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }
zstd = { workspace = true }

[lints]
workspace = true

[features]
default = []
