[package]
name = "timsrust-core"
version = "0.1.1"
edition = "2024"
description = "Core data types and abstractions for timsTOF data"
license = "Apache-2.0"

[dependencies]
# timsrust-io = { workspace = true, optional = true }
timsrust-utils = { workspace = true }
rayon = { workspace = true }
filemanager = { workspace = true, default-features = true, optional = true }

[lints]
workspace = true

[features]
# io = ["timsrust-io"]
io = ["filemanager"]
