[package]
name = "timsrust"
version = "0.5.3"
edition = "2024"
description = "A crate to read Bruker timsTOF data"
license = "Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/timsrust"
repository = "https://github.com/mannlabs/timsrust"
homepage = "https://github.com/mannlabs/timsrust"
categories = ["accessibility", "data-structures", "parsing", "science"]
keywords = ["MS", "LC-TIMS-TOF", "PASEF"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
timsrust-sdk = { workspace = true, optional = true }
timsrust-patched = { workspace = true, optional = true }
timsrust-centroid = { workspace = true }
timsrust-core = { workspace = true, features = ["io"] }
timsrust-minitdf = { workspace = true }
timsrust-parquet-spectra = { workspace = true }
timsrust-tdf = { workspace = true }
timsrust-tsf = { workspace = true }
thiserror = { workspace = true }
rayon = { workspace = true }

[dev-dependencies]
timsrust-mgf = { workspace = true }

[lints]
workspace = true

[features]
sdk = ["timsrust-sdk"]
patched = ["timsrust-patched"]

[[example]]
name = "with_sdk"
required-features = ["sdk"]

[[example]]
name = "with_patched"
required-features = ["patched"]
