[package]
name = "timsrust-sdk"
version.workspace = true
edition.workspace = true
build = "build.rs"
description = "Bruker TimsData SDK bindings for native timsTOF data access"
license = "Apache-2.0"

[dependencies]
timsrust-core = { workspace = true, features = ["io"] }
serde = { workspace = true, features = ["derive"] }
libc = { workspace = true }

[lints]
workspace = true
