[package]
name = "timsrust-parquet-spectra-cli"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[dependencies]
timsrust = { workspace = true }
timsrust-core = { workspace = true }
clap = { workspace = true, features = ["cargo", "derive"]}
env_logger = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "timsrust-parquet-spectra-cli"
path = "src/main.rs"

[features]
sdk = ["timsrust/sdk"]
patched = ["timsrust/patched"]
