[package]
name = "timsrust-minitdf"
version = "0.1.4"
edition = "2024"
description = "Reader for the ProteoScape miniTDF timsTOF file format"
license = "Apache-2.0"

[dependencies]
timsrust-core = { workspace = true, features = ["io"] }
serde = { workspace = true, features = ["derive"] }
zstd = { workspace = true }
thiserror = { workspace = true }
bytemuck = { workspace = true }

[lints]
workspace = true
