[package]
name = "timsrust-mgf-cli"
version = "0.1.3"
edition = "2024"
publish = false

[dependencies]
timsrust = { workspace = true }
timsrust-mgf = { workspace = true }
timsrust-cli-core = { workspace = true }

[lints]
workspace = true

[[bin]]
name = "timsrust-mgf-cli"
path = "src/main.rs"

[features]
patched = ["timsrust/patched"]
sdk = ["timsrust/sdk"]
